In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [7]:
df=pd.read_csv("Advertising.csv")
df=df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [11]:
X = df.drop('sales',axis=1)
y = df[["sales"]]
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [10]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [12]:
#Statsmodels ile model kurmak

In [14]:
import statsmodels.api as sm

In [15]:
lm = sm.OLS(y,X)

In [16]:
model=lm.fit()

In [17]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Tue, 09 Feb 2021   Prob (F-statistic):                   2.43e-171
Time:                        09:07:01   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [18]:
# scikit learn ile model kurmak

In [20]:
lm = LinearRegression()

In [22]:
model1 = lm.fit(X,y)

In [23]:
model1.intercept_

array([2.93888937])

In [24]:
model1.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

### tahmin

In [30]:
yeni_veri=[[30],[10],[40]]
yeni_veri=pd.DataFrame(yeni_veri).T
yeni_veri

0   1   2
0  30  10  40

In [33]:
model1.predict(yeni_veri)

array([[6.15562918]])

In [34]:
from sklearn.metrics import mean_squared_error

In [35]:
model1.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [37]:
MSE = mean_squared_error(y,model1.predict(X))
MSE

2.784126314510936

In [38]:
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697

In [39]:
# Sinama seti

In [40]:
from sklearn.model_selection import train_test_split

In [51]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=99)

In [52]:
lm=LinearRegression()
model2=lm.fit(X_train,y_train)

In [53]:
# Egitim hatasi
np.sqrt(mean_squared_error(y_train,model2.predict(X_train)))

1.7236824822650751

In [54]:
# Test hatasi
np.sqrt(mean_squared_error(y_test,model2.predict(X_test)))

1.4312783138301641

In [55]:
#k-katli cv
from sklearn.model_selection import cross_val_score

In [59]:
# cv mse
np.mean(-cross_val_score(model2,X_train,y_train,cv=10,scoring="neg_mean_squared_error"))

3.317028974234127

In [60]:
# cv rmse
np.sqrt(np.mean(-cross_val_score(model2,X_train,y_train,cv=10,scoring="neg_mean_squared_error")))

1.821271252239525

AttributeError: module 'pandas' has no attribute 'linspace'